# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
provider "aws" {
  region = "us-east-1"
  profile = "default"
  insecure = false
  default_tags = {
    Terraform = true
  }
  # skip credentials validation via the STS API
  skip_credentials_validation = true
  # skip validating the region
  skip_region_validation = true
  # skip the AWS Metadata API check
  skip_metadata_api_check = true
  # skip getting the supported EC2 platforms
  skip_get_ec2_platforms = true

}
provider "google" {
  region = "us-west1"
  project = "acme"
}
